services:
  mongodb:
    image: mongo:6
    container_name: mongodb
    restart: always
    ports:
      - '27017:27017'
    volumes:
      - mongodb_data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: secret

  redis:
    image: redis:7
    container_name: redis
    restart: always
    ports:
      - '6379:6379'
    environment:
      REDIS_PASSWORD: mysecretpassword
    command: redis-server --requirepass mysecretpassword

  app:
    build: .
    container_name: nestjs-app
    restart: always
    ports:
      - '3000:3000'
    depends_on:
      - mongodb
      - redis
    environment:
      MONGO_URI: mongodb://admin:secret@mongodb:27017/mydatabase?authSource=admin
      REDIS_URI: redis://default:mysecretpassword@redis:6379
    command: npm run start:prod

volumes:
  mongodb_data:
